- id: '1648210287941'
  alias: Jasper weg apparaten uit
  description: Jasper weg apparaten op zijn kamer uit
  trigger:
  - platform: zone
    entity_id: person.jasper_bierlaagh
    zone: zone.home
    event: leave
  action:
  - service: light.turn_off
    target:
      device_id:
      - c19a67f8e10d3581c13d4391adc7e833
      - 23885973c5decd67f87e59d48115246d
      - 92715a7c2d20dd04cf8871c42865a03e
    data: {}
  - service: notify.mark_telegram
    data:
      message: Jasper Left Home
      title: Jasper weg
  mode: single
- id: '1653184899270'
  alias: Waterbed_altijd_aan
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: d63b212e73cd90bd00fb5baea1a1d89e
    entity_id: switch.plug_tuya_power_metered_17_waterbed
    domain: switch
  condition: []
  action:
  - device_id: d63b212e73cd90bd00fb5baea1a1d89e
    domain: select
    entity_id: select.plug_tuya_power_metered_17_waterbed_indicator_mode
    type: select_option
    option: 'on'
  - service: telegram_bot.send_message
    data:
      message: Waterbed automatisch aangezet
      title: 'Waterbed automation triggered '
  mode: single
- id: '1656713056510'
  alias: zwembadpomp on
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  - platform: time
    at: '14:00:00'
  condition: []
  action:
  - device_id: 80204471ca7f905c3e0b1d4c3274ff71
    domain: rfxtrx
    type: send_command
    subtype: 'On'
  mode: single
- id: '1656713133264'
  alias: zwembadpomp off
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - device_id: 80204471ca7f905c3e0b1d4c3274ff71
    domain: rfxtrx
    type: send_command
    subtype: 'Off'
  mode: single
- id: '1659816310485'
  alias: wasdroger_altijd_aan
  description: ''
  trigger:
  - platform: device
    device_id: 7e2318529a1a26b28d70eb84b6397b14
    domain: select
    entity_id: select.plug_tuya_power_metered_14_wasdroger_indicator_mode
    type: current_option_changed
    to: 'off'
  condition: []
  action:
  - device_id: 7e2318529a1a26b28d70eb84b6397b14
    domain: select
    entity_id: select.plug_tuya_power_metered_14_wasdroger_indicator_mode
    type: select_option
    option: 'on'
  - service: telegram_bot.send_message
    data:
      message: wasdroger automatisch aangezet
      title: 'wasdroger (on) automation triggered '
  mode: single
