---
# Welcome to my Home Assistant configuration!
#
# Don't be scared by the size of my configuration file...
# It is probably the smallest you've ever seen.
#
# My system is very modular and very differently structured
# compared to other configurations you'll find online.
#
# Basically, each file in the repository does 1 (one, uno, eins)
# thing only! Click through it, you'll get it pretty fast.
#
# The configuration.yaml is only used to bootstrap the system.
<<<<<<< HEAD
# new input
=======
#
<<<<<<< HEAD
>>>>>>> fc29760c (Initial commit)
=======
# added this line to test new git status
# new test to see if changes work
# woukd this also work
#last test 16:03 25 okt
>>>>>>> a4097034 (another sync 1618)
homeassistant:
  # Load packages
  packages: !include_dir_named integrations