---
#
# 
#
sensor:
  - name: watermeter_tellerstand
    unique_id: watermeter_tellerstand
    unit_of_measurement: L
    device_class: water
    state: >- 
        {{states.sensor.water_meter_teller_stand.state | float + 1963005 }}
    state_class: total_increasing